'''A collection of useful functions for bioinformatics data analysis.

This library contains many functions and methods I use again and again in different analyses including:
- api: enrichr, l1000fwd, ...
- clustering: silhouette analysis, ...
- dge: various differential gene expression techniques including chdir, lima_voom, ..
- harmonization: transcript to gene conversions, ...
- normalization: log, cpm, zscore, filterByExpr, quantile, ...
- parse: gmt, suerat ready files, ...
- utils: fetch_save_read, merge, ...
'''

# Lazy loading submodules to defer optional dependency imports (https://peps.python.org/pep-0810/)
import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach(
    __name__,
    submodules=['api', 'clustering', 'dge', 'harmonization', 'normalization', 'parse', 'plotting', 'setup', 'utils'],
)
